bin_bank/urls.py
from django.urls import path
from bin_bank.views import *
app_name = 'bin_bank'

urlpatterns = [
    path('', homepage, name='homepage'),  # TODO : homepage
    path('json/user_login', user_login_data, name='user_login_data'),
    path('login/', login_user, name='login'),
    path('login/ajax', ajax_login_user, name='ajax_login_user'),
    path('register/', register, name='register'),
    path('register/ajax', ajax_register, name='ajax_register'),
    path('logout/', logout_user, name='logout'),
    path('logout/ajax', ajax_logout_user, name='ajax_logout_user'),
    path('leaderboard/', leaderboard, name='leaderboard'),
    path('leaderboard/add-support-message', add_support_message, name='add_support_message'),
    path('leaderboard/add-support-message-app', add_support_message_post, name='add_support_message_post'),
    path('leaderboard/cari', find_username_menu, name='find_username_menu' ),
    path('leaderboard/cari/<str:username>', find_username, name='find_username' ),  # type: ignore
    path('history/', show_history, name='show_history'),
    path('post-feedback-json/', post_feedback_json, name='post_feedback_json'),
    path('feedback-json/', show_feedback_json, name='show_feedback_json'),
    path('article-json/', show_article_json, name='show_article_json'),
    path('add-feedback/', add_feedback, name='add_feedback'),
    path('json/', show_transaction_user, name='show_transaction_user'),
    path('json/ongoing/', show_transaction_user_ongoing, name='show_transaction_user_ongoing'),
    path('json/success/', show_transaction_user_success, name='show_transaction_user_success'),
    path('json/range/', show_transaction_user_range, name='show_transaction_user_range'),
    path('json/search/', show_transaction_user_specific, name='show_transaction_user_specific'),
    path('json/leaderboard', show_leaderboard, name='show_leaderboard'),
    path('json/support-message', show_support_message, name='show_support_message'),
    path('update-transaction/<int:id>', update_transaction, name='update_transaction'),
    path('deposit_sampah/', deposit_sampah, name='deposit_sampah'),
    path('deposit_sampah/add_transaction/', add_transaction, name='add_transaction'),
    path('deposit_sampah/add_transaction_post/', add_transaction_post, name='add_transaction_post'),
    path('deposit_sampah/post_transaction_json/', post_transaction_json, name='post_transaction_json'),
    path('deposit_sampah/show_transaction/', show_transaction, name='show_transaction'),
    path('deposit_sampah/delete_transaction/', delete_transaction, name='delete_transaction'),
    path('json/post/', show_transaction_user_post, name='show_transaction_user_post'),
    path('json/post/ongoing', show_transaction_user_ongoing_post, name='show_transaction_user_ongoing_post'),
    path('json/post/success', show_transaction_user_success_post, name='show_transaction_user_success_post'),
    path('json/post/range', show_transaction_user_range_post, name='show_transaction_user_range_post'),
    path('json/post/branch', show_transaction_user_branch_post, name='show_transaction_user_branch_post'),
    path('update-transaction-post/', update_transaction_post, name='update_transaction_post'),

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bin_bank.urls')),
]

bin_bank/models.py
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.db import models
from django.utils import timezone
from xmlrpc.client import MAXINT, MININT
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db import models

from project_django import settings

User = settings.AUTH_USER_MODEL


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(default=timezone.now)
    amountKg = models.IntegerField()
    branchName = models.CharField(max_length=255)
    isFinished = models.BooleanField(default=False)


class MyUserManager(BaseUserManager):
    def create_user(self, username, password=None):
        user = self.model(
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            password=password,
            username=username,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(max_length=20, unique=True)
    points = models.IntegerField(default=0)

    is_admin = models.BooleanField(default=False)
    objects = MyUserManager()

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Article(models.Model):
    title = models.CharField(max_length=100)
    intro = models.TextField()
    image = models.CharField(max_length=500)
    source = models.URLField()

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, default=None)
    date = models.DateField(default=timezone.now)
    subject = models.CharField(max_length=255)
    feedback = models.TextField()

class SupportMessage(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    message = models.TextField()

bin_bank/views.py
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers

from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from bin_bank.models import Article, Feedback, MyUser, SupportMessage, Transaction
from bin_bank.forms import RegisterForm, SupportMessageForm,FeedbackForm, RegisterForm, FindTransactionForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
User = get_user_model()

# Fungsi Autentikasi
@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            auth_login(request, user)
            # Redirect to a success page.
            return redirect('bin_bank:homepage')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('bin_bank:homepage') #response

@csrf_exempt
def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('bin_bank:login')

    context = {'form': form}
    return render(request, 'register.html', context)

# Asynchronous JavaScript (AJAX) login, register, and logout view 
@csrf_exempt
def ajax_login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                # Redirect to a success page.
                return JsonResponse({
                "status": True,
                "username":username,
                "message": "Successfully Logged In!"
                # Insert any extra data if you want to pass data to Flutter
                }, status=200)
            else:
                return JsonResponse({
                "status": False,
                "message": "Failed to Login, Account Disabled."
                }, status=401)

        else:
            return JsonResponse({
            "status": False,
            "message": "Failed to Login, check your email/password."
            }, status=401)
    
@login_required(login_url='/login/')
def user_login_data(request):
  login_user_data = User.objects.filter(id=request.user.id)
  return HttpResponse(serializers.serialize('json', login_user_data), content_type="application/json")

@csrf_exempt
def ajax_logout_user(request):
    try:
        logout(request)
        return JsonResponse({
            "status": True,
            "message": "Successfully Logged out!",
        }, status=200)
    except:
        return JsonResponse({
          "status": False,
          "message": "Failed to Logout"
        }, status=401)

@csrf_exempt
def ajax_register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return JsonResponse({
            "status": True,
            "message": "Successfully Register"
            # Insert any extra data if you want to pass data to Flutter
            }, status=200)
        else :
            error_register_form = form.errors

            return JsonResponse({
            "status": False,
            "message": error_register_form.as_json()
            }, status=401)
    
    return JsonResponse({
            "status": False,
            "message": "Register Fail"
            }, status=401)

# Fungsi untuk menampilkan homepage
def homepage(request):
    username = request.user.username
    total_feedback = Feedback.objects.count()
    data_transaction = Transaction.objects.all()
    data_article = Article.objects.all()
    if total_feedback > 4:
        data_feedback = Feedback.objects.all()[:4]
    else:
        data_feedback = Feedback.objects.all()

    total_waste = 0
    for transaction in data_transaction:
        total_waste += transaction.amountKg

    context = {
        'username': username,
        'shared_story': total_feedback,
        'waste_collected': total_waste,
        'articles': data_article,
        'feedbacks': data_feedback
    }

    return render(request, 'homepage.html', context)

@login_required(login_url='/login/')
def add_feedback(request):
    username = request.user.username
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid(): # Kondisi data pada field valid
            new_feedback = Feedback(
                user = request.user,
                subject = form.cleaned_data['subject'], 
                feedback = form.cleaned_data['feedback'],
            )
            new_feedback.save() # Menyimpan task ke database
            return HttpResponse(b"CREATED", status=201)
    else:
        form = FeedbackForm()
    
    context = {'form':form, 'username':username}
    return render(request, "feedback.html", context)

@csrf_exempt
def post_feedback_json(request):
    if request.method == "POST":
        subject = request.POST["subject"]
        feedback = request.POST["feedback"]
        user = request.POST["user"]
        user = MyUser.objects.filter(username=user)
        user = user[0]
        new_feedback = Feedback(
                user = user,
                subject = subject,
                feedback = feedback,
        )
        new_feedback.save()
        context = {'message': 'SUCCESS'}
    else:
        context = {'message': 'FAILED'}

    return JsonResponse(context)

# Fungsi untuk mengembalikan seluruh data task dalam bentuk JSON
def show_feedback_json(request):
    data_feedback = Feedback.objects.all()
    return HttpResponse(serializers.serialize('json', data_feedback), content_type='application/json')

def show_article_json(request):
    data = Article.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login/')
def show_history(request):
    # TODO: Sessions
    form = FindTransactionForm()
    context = {
        'username': request.user.username,
        'form': form
    }
    return render(request, "history.html", context)


@login_required(login_url='/login/')
def update_transaction(request, id):
    transaction_list = Transaction.objects.filter(id=id)
    transaction = transaction_list[0]
    transaction.isFinished = True
    transaction.save()
    request.user.points += transaction.amountKg
    request.user.save()
    return redirect('bin_bank:show_history')


@login_required(login_url='/login/')
def show_transaction_user(request):
    transactions = Transaction.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", transactions), content_type="application/json")


@login_required(login_url='/login/')
def show_transaction_user_ongoing(request):
    transactions = Transaction.objects.filter(user=request.user, isFinished=False)
    return HttpResponse(serializers.serialize("json", transactions), content_type="application/json")


@login_required(login_url='/login/')
def show_transaction_user_success(request):
    transactions = Transaction.objects.filter(user=request.user, isFinished=True)
    return HttpResponse(serializers.serialize("json", transactions), content_type="application/json")


@login_required(login_url='/login/')
def show_transaction_user_range(request):
    if request.method == "POST":
        transactions = Transaction.objects.filter(
            user=request.user,
            amountKg__range=(request.POST["Min"],
                             request.POST["Max"]))
        return HttpResponse(serializers.serialize("json", transactions), content_type="application/json")
    return HttpResponse("Invalid method", status_code=405)


@login_required(login_url='/login/')
def show_transaction_user_specific(request):
    form = FindTransactionForm(request.POST)
    if form.is_valid():
        form = form.save(commit=False)
        transactions = Transaction.objects.filter(user=request.user, branchName=form.branchName)
        return HttpResponse(serializers.serialize("json", transactions), content_type="application/json")
    return HttpResponse("Invalid method")


@login_required(login_url='/login/')
def deposit_sampah(request):
    username = request.user.username
    return render(request, "deposit_sampah.html", {'username':username})


@login_required(login_url='/login/')
def add_transaction(request):
    if request.method == 'POST':
        amountKg = request.POST.get('amountKg')
        branchName = request.POST.get('branchName')
        response_data = {}

        transaction = Transaction(amountKg=amountKg, branchName=branchName, user=request.user)
        transaction.save()


        response_data['result'] = 'Create post successful!'
        response_data['username'] = transaction.user.username
        response_data['pk'] = transaction.pk
        response_data['date'] = transaction.date.strftime('%B %d, %Y %I:%M %p')
        response_data['amountKg'] = transaction.amountKg
        response_data['branchName'] = transaction.branchName
        response_data['isFinished'] = transaction.isFinished

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(

bin_bank/templates/history.html
{% extends 'base.html' %}

{% load static %}
{% block meta %}
<title>History</title>
{% endblock meta %}


{% block content %}
<!-- Section: Design Block -->
<body style= "padding-top: 100px"data-bs-spy="scroll" data-bs-target=".navbar">
  
{% include 'navbar.html' %}
  <h1 class="text-center">Cari Transaksi</h1>
  <link rel="stylesheet" href="{% static 'bin_bank.css' %}"> 
  
    <div class="col-12 section-intro text-center">
      <form method="POST" action="" id="searchtransaction">
        <div>
          <div class="divider"></div>
        </div>
        <div class="col-12 section-intro text-center">    
          <h5>Berdasarkan Cabang</h5>  
          {% csrf_token %}
          {{form.branchName}}
          
          {{ formset.non_form_errors }}

          {% if form.amountKg.errors %}
          <span class="text-danger">{{ form.amountKg.errors }} </span>
          {% endif %} 

          {% if form.branchName.errors %}
            <span class="text-danger">{{ form.branchName.errors }} </span>
          {% endif %} 
        </div>
        <div>
          <input type="submit" class="btn btn-main" value="Cari" id="carispesifikBtn">
        </div>
      </form>
    </div>
    
    <div class="col-12 section-intro text-center">
      <form method="POST" action="" id="filterTransaction">
        {% csrf_token %}
        <div class="col-12 section-intro text-center">
          <h5>Berdasarkan Berat</h5>
          <label class="form-label" for="id_batasbawah" ></label>
          <input type="number" id="id_batasbawah" name="Min" min="0" placeholder="Minimal Kilogram"></input>
          
          <label class="form-label" for="id_batasatas"></label>
          <input type="number" id="id_batasatas" name="Max" max="99999999999999" placeholder="Maksimal Kilogram"></input>
        </div> 
        <div class="text-center">
          <input type="submit" class="btn btn-main" value="Cari" id="cariBtn">
          <input type="submit" class="btn btn-main" value="Reset" id="resetBtn">
        </div>
      </form>
    </div>
   
  

    <div class="col-12 section-intro text-center">
        <h5>Berdasarkan Status</h5>
        <input type="submit" class="btn btn-main" value="Semua" id="filterall">
        <input type="submit" class="btn btn-main" value="Sedang Berlangsung" id="filterongoing">
        <input type="submit" class="btn btn-main" value="Berhasil" id="filtersucess">
    </div>
    <div class="col-11 section-intro text-center mx-auto" id="containerMain"></div> 
    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous">
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <script>
    var maxKg = 0
    $(document).ready(() => {
      $("#id_branchName")[0].placeholder="Nama Cabang"
      $("#cariBtn").click(setrange)
      $("#carispesifikBtn").click(getDataSpecific)
      $("#filterongoing").click(getDataOngoing)
      $("#filtersucess").click(getDataSuccess)
      $("#filterall").click(getDataDefaultButton)
      $("#resetBtn").click(resetRangeFilter)
      getDataDefault()
    })

    function updateTransaction(id) {
      $.ajax({
        type: 'POST',
        url: '/update-transaction/'+ id,
        beforeSend: function(xhr) {
          xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: () => {
          $("#"+id).remove()
          $("#cardStatus"+id)[0].innerHTML = "Berhasil"
        }
        });
    }


    function getDataSpecific(e) {
      e.preventDefault()
      $.ajax({
        type: 'POST',
        url: '/json/search/',
        data: $("#searchtransaction").serialize(), 
        success: function(data) {
            console.log(data)
            showDefault(data)
            
          },
          dataType: 'json'
        })
    }

    function resetRangeFilter(e){
      e.preventDefault()
      $("#filterTransaction")[0].reset();
      $.get("{% url 'bin_bank:show_transaction_user' %}", function (data) {
        showDefault(data)
      })
    }
    function getDataDefaultButton(e){
      e.preventDefault()
      $.get("{% url 'bin_bank:show_transaction_user' %}", function (data) {
        showDefault(data)
      })
    }

    function getDataDefault(){
      $.get("{% url 'bin_bank:show_transaction_user' %}", function (data) {
        showDefault(data)
      })
      
    }

    function getDataOngoing(e){
      e.preventDefault()
      $.get("{% url 'bin_bank:show_transaction_user_ongoing' %}", function (data) {
        showDefault(data)
      })
    }

    function getDataSuccess(e){
      e.preventDefault()
      $.get("{% url 'bin_bank:show_transaction_user_success' %}", function (data) {
        showDefault(data)
      })
    }


    function setrange(e) {
      e.preventDefault()
      var batasBawah = $("#id_batasbawah")[0]
      var batasAtas = $("#id_batasatas")[0]

      //Handle jika input kosong, set max dan min
      if (batasBawah.value==""){
        batasBawah.value=0
      }
      if (batasAtas.value==""){
        batasAtas.value = maxKg
      }

      $.ajax({
        type: 'POST',
        url: '/json/range/',
        data: $("#filterTransaction").serialize(), 
        success: function(data) {
            showDefault(data)
          },
          dataType: 'json'
        });
      
    }

    function showNodata(){
      var container = document.getElementById("containerMain")
      container.innerHTML = ""
      var messageTitle = document.createElement("h2")
      messageTitle.innerHTML = "Oops, nggak ada transaksi yang sesuai filter"

      var message = document.createElement("h5")
      message.innerHTML = "Coba reset atau ubah filter kamu, ya."
      
      container.appendChild(messageTitle)
      container.appendChild(message)
    }

    function showDefault(data){
      
      var container = document.getElementById("containerMain")
      container.innerHTML = ""
      
      if (data.length == 0) {
        showNodata()
        return
      }
      data.forEach(element => {
        var fields = element.fields
        var user = fields.user 
        var date = fields.date 
        var amountKg = fields.amountKg 
        var branchName = fields.branchName 
        var isFinished = fields.isFinished 

        var card = document.createElement("div")
        card.className = "card mb-3 py-0"

        var cardContent = document.createElement("div")
        cardContent.className = "row g-0 d-flex align-items-center justify-content-center"
        
        var cardBody = document.createElement("div")
        cardBody.className = "card-body py-5 px-md-5"
      
        
        if (amountKg>maxKg) {
          maxKg = amountKg
        }
        var cardHeader = document.createElement("h2")
        cardHeader.className = "card-title"
        cardHeader.innerHTML = amountKg+ " Kg" + " (" + date.substring(0,date.indexOf("T")) + ")" 

        var cardText = document.createElement("p")
        cardText.className = "card-text"
        cardText.innerHTML = "Cabang: " + branchName
        
        var cardStatus = document.createElement("h5")
        
        cardStatus.id = "cardStatus" + element.pk
        cardStatus.className = "card-text"
        cardStatus.innerHTML = (isFinished) ? 'Berhasil' : 'Sedang Berlangsung' 
        var buttonUpdate = document.createElement("button")
        
        
        cardBody.appendChild(cardHeader)
        cardBody.appendChild(cardText)
        cardBody.appendChild(cardStatus)
        
        if (!isFinished) {
          buttonUpdate.className = "btn btn-main"
          buttonUpdate.onclick = function () {
            updateTransaction(element.pk)
          };
          buttonUpdate.innerHTML = "Selesaikan Transaksi"
          buttonUpdate.id = element.pk
          cardBody.appendChild(buttonUpdate)
        }

        cardContent.appendChild(cardBody)
        card.appendChild(cardContent)
        container.appendChild(card)

        //document.body.appendChild(container)
        
      })
    }
  </script>
<footer class="py-4">
  <div class="container">
      <div class="row">
          <div class="col-md-6">
              <p class="mb-0">Copyright © 2022. Bin Bank</p>
          </div>
          <div class="col-md-6 text-md-end">
              <div>
                  <a href="#"><i class="bx bxl-facebook-circle"></i></a>
                  <a href="#"><i class="bx bxl-twitter"></i></a>
                  <a href="#"><i class="bx bxl-dribbble"></i></a>
                  <a href="#"><i class="bx bxl-instagram"></i></a>
                  <a href="#"><i class="bx bxl-github"></i></a>
              </div>
          </div>
      </div>
  </div>
</footer>
</body>
{% endblock content %}

bin_bank/templates/leaderboard_search.html
{% extends 'base.html' %}

{% block meta %}
<title>Leaderboard</title>
{% endblock meta %}

{% block content %}

    {% include 'navbar.html' %}

    <section>
        <div class="container">
                <div class="row">
                    <div class="col-12 section-intro text-center">
                        <h1>Cari user berdasarkan username</h1>
                        <div class="divider"></div>
                        {% if is_found == True %}
                            <p>{{searched_user}} berada di peringkat {{rank}}</p>
                        {% elif is_found == "" %}
                        {% else %}
                            <p>{{searched_user}} tidak ditemukan</p>
                        {% endif %}
                        
                        <form method="POST">
                            <input type="text" name="textinput">
                            <div class="text-center">
                                <br>
                                <button id="findButton" class="btn btn-main" type="submit">Search</button>
                            </div>
                        </form>
                    </div>
                </div>
        </div>
    </section>

{% endblock content %}

bin_bank/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'bin_bank.css' %}">
<section class="main">
	<div class="layer">
        <div class="container text-black text-center">
            <div class="row">
                <div class="col-12">
                        <p class="display-5">LOGIN</p>
                </div>
            </div>
        </div>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="mx-auto card align-items-center mb-3 w-50" style="background-color: black;" >
                <div class="card-body">
                        <table>
                            <tr>
                                <td style="color: white;">Username: </td>
                                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                            </tr>
                                    
                            <tr>
                                <td style="color: white;">Password: </td>
                                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                            </tr>

                            <tr>
                                <td></td>
                                <td><input class="btn btn-main" type="submit" value="Login" style="margin-top: 30px; margin-left: 25%;" /></td>
                            </tr>
                        </table>
                </div>
            </div>
        </form>
        <div class="text-center" style="margin-top: 15px">
            Belum mempunyai akun? <a href="{% url 'bin_bank:register' %}">Buat Akun</a>
        </div>
       
    <div class="text-center" style="margin-top: 15px">
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
    </div>
        
     

</div>

{% endblock content %}

bin_bank/templates/navbar.html
{% load static %}
<!-- CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'bin_bank.css' %}">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- Bootstrap Font Icon CSS -->
<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

<!-- Navbar section -->
<body data-bs-spy="scroll" data-bs-target=".navbar">
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="{% url 'bin_bank:homepage' %}">BIN BANK.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bin_bank:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bin_bank:leaderboard' %}">Leaderboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bin_bank:deposit_sampah' %}">Donate</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bin_bank:show_history' %}">History</a>
                </li>
                <li class="nav-item">
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{username}}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                      <a href="{% url 'bin_bank:logout' %}"><button class="dropdown-item" type="button">Logout</button></a>
                    </div>
                </div>
                {% endif %}
                {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'bin_bank:login' %}">Login</a>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>